# Generated by Django 3.2.5 on 2021-07-11 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='nama-kategori')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='judul')),
                ('author', models.CharField(default='admin', max_length=255, verbose_name='pencipta')),
                ('description', models.TextField(blank=True, verbose_name='deskripsi')),
                ('image', models.ImageField(upload_to='images/', verbose_name='gambar')),
                ('slug', models.SlugField(max_length=255, verbose_name='product-slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='harga')),
                ('in_stock', models.BooleanField(default=True, verbose_name='stok')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='product_creator')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_by',),
            },
        ),
    ]
