"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1vdgbbpnh-dpyzcz3$c7&-e5wu%ip0s&m_s1t0!&$$ucb02=-3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecommerce.apps.catalogue',
    "ecommerce.apps.account",
    "ecommerce.apps.checkout",
    "ecommerce.apps.basket",
    "ecommerce.apps.orders",
    'mptt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.apps.catalogue.context_processors.categories',
                'ecommerce.apps.basket.context_processors.basket',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

#Basket session ID
BASKET_SESSION_ID = "basket"

# # Stripe Payment
# PUBLISHABLE_KEY = 'pk_test_51K6UYoJtaYn6oIYDaljcQ9JvftFKy6as4l0jSFRFCOL31wS9lepTffk3SkwkoCRYS82Ed15fPZxCSbj6o9jb6sLK00c1r3nNQF'
# SECRET_KEY = 'sk_test_51K6UYoJtaYn6oIYDB0iqTO5sx6MQvJLZzSHOBRW4TCjQOGgcFfSiebLAzHVIDJgsSauFpLyGkwkBIP2XPlofG3tZ00cEGplIfd'
# STRIPE_ENDPOINT_SECRET = 'whsec_ixaR99wdK9VFwr9WNf7PazkIwimAB0IG' # Dari stripe CLI
# # stripe listen --forward-to localhost:8000/payment/webhook/

# # Stripe Payment --> delete during part 8 paypal
# os.environ.setdefault('STRIPE_PUBLISHABLE_KEY', 'pk_test_51K6UYoJtaYn6oIYDaljcQ9JvftFKy6as4l0jSFRFCOL31wS9lepTffk3SkwkoCRYS82Ed15fPZxCSbj6o9jb6sLK00c1r3nNQF')
# STRIPE_SECRET_KEY = 'sk_test_51K6UYoJtaYn6oIYDB0iqTO5sx6MQvJLZzSHOBRW4TCjQOGgcFfSiebLAzHVIDJgsSauFpLyGkwkBIP2XPlofG3tZ00cEGplIfd'
# STRIPE_ENDPOINT_SECRET = 'whsec_ixaR99wdK9VFwr9WNf7PazkIwimAB0IG' # Dari stripe CLI
# # stripe listen --forward-to localhost:8000/payment/webhook/

# Custom user model
# AUTH_USER_MODEL = "account.Customer"
# AUTH_USER_MODEL = "account.UserBase" #during UUID
AUTH_USER_MODEL = "account.Customer"
LOGIN_REDIRECT_URL = "/account/dashboard"
LOGIN_URL = "/account/login/"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email setting
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
